name: echo-bot
version: 0.1.0.0

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - http-conduit
  - http-types
  - dhall
  - bytestring
  - text
  - text-manipulate
  - random
  - lens
  - lens-aeson
  - time
  - mtl
  - containers
  - unordered-containers
  - raw-strings-qq

library:
  ghc-options:
    - -Wall
  exposed-modules:
    - LibModule
    - Telegram
    - Vk
  source-dirs: src

executables:
  echo-bot-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -Wall
    dependencies:
      - echo-bot
    when:
      - condition: false
        other-modules: Paths_echo_bot

tests:
  spec:
    defaults: hspec/hspec@master
    dependencies:
      - echo-bot
      - network-uri
      - split
    when:
      - condition: false
        other-modules: Paths_echo_bot
